# GET http://localhost:3003/api/blogs

#  POST http://localhost:3003/api/blogs 
#  content-type: application/json
 
# {
#     "title": "Accountability in Software Development",
#     "author": "Kent Beck",
#     "url": "https://medium.com/@kentbeck_7670/accountability-in-software-development-375d42932813",
#     "like": 646
# }

# GET http://localhost:3003/api/users

#  POST http://localhost:3003/api/users
#  content-type: application/json

# {
#     "name":  "ali-akbari",
#     "username": "ali",
#     "password": "123"
# }

POST http://localhost:3000/api/testing/reset