# delete http://localhost:3001/api/persons/649f027417d53d1c1da4455c

# GET http://localhost:3001/info

# GET http://localhost:3001/api/persons

# GET http://localhost:3001/api/persons/649efb20c477f104e511896b

# POST http://localhost:3001/api/persons
# content-type: application/json

# {
#     "name": "mamad",
#     "number": 911
# }